---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an Amazon RDS PostgreSQL instance"

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: "samplePostgresInstanceRds"
    MinLength: 1
    MaxLength: 63
    
  DBName:
    Type: String
    Description: "sampleMyDatabase"
    MinLength: 1
    MaxLength: 64
    
  DBUsername:
    Type: String
    Description: "kanikasample"
    MinLength: 1
    MaxLength: 16
    
  DBPassword:
    Type: String
    Description: "kanikasample123456"
    MinLength: 8
    MaxLength: 41
    NoEcho: true
    

Resources:
  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: "200"
      MaxAllocatedStorage: "1000"
      AvailabilityZone: "us-east-1a"
        
      EnableIAMDatabaseAuthentication: "True"
      Port: "5432"
      # Tags: 
      #   - Tags
      DBInstanceClass: "db.t3.micro"
      Engine: "postgres"
      EngineVersion: "15.2"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      PubliclyAccessible: false
      StorageType: "gp2"

  
  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security Group for the RDS instance"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "5432"
          ToPort: "5432"
          CidrIp: "0.0.0.0/0"
          


  # MyIAMRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: String
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
        
            
Outputs:
  DatabaseInstancePort:
    Value: "5432"
  SecurityGroupId:
    Value: !Ref RDSSecurityGroup
  
