---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an Amazon RDS PostgreSQL instance"

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: "postgres-instance-rds"
    MinLength: 1
    MaxLength: 63
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters and hyphens"
  DBName:
    Type: String
    Description: "my_database"
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Za_zA_Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters"
  DBUsername:
    Type: String
    Description: "kanika"
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter, and can include numeric and alpha numeric characters"
  DBPassword:
    Type: String
    Description: "**********"
    MinLength: 8
    MaxLength: 41
    NoEcho: true
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must contain only alphanumeric characters and normal letters"

Resources:
  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: "200"
      MaxAllocatedStorage: "1000"
      AssociatedRoles : [ DBInstanceRole]
      AvailabilityZone : "us-east-1"
      DBSecurityGroups: 
    - String
      DBSubnetGroupName: String
      EnableIAMDatabaseAuthentication: "True"
      NetworkType: String
      Port: "5432"
      Tags: 
    - Tag
      VPCSecurityGroups: 
    - String
      DBInstanceClass: "db.t3.micro"
      Engine: "PostgreSQL"
      EngineVersion: "11.10"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      PubliclyAccessible: false
      StorageType: "gp2"

Outputs:
  DBEndpointAddress:
    Description: "The endpoint address of the RDS instance"
    Value: !Join ["", ["postgres://", !Ref DBUsername, ":", !Ref DBPassword, "@", !GetAtt DBInstance.Endpoint.Address, "/", !Ref DBName]]
